/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as proxypadDeployerSol from "./ProxypadDeployer.sol";
export type { proxypadDeployerSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as staking from "./staking";
export type { staking };
import type * as utils from "./utils";
export type { utils };
export type { CasterNFT } from "./CasterNFT";
export type { PrizePool } from "./PrizePool";
export type { RoyaltyBank } from "./RoyaltyBank";
export type { Ticket } from "./Ticket";
