/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iManagerSol from "./IManager.sol";
export type { iManagerSol };
import type * as proxypadDeployerSol from "./ProxypadDeployer.sol";
export type { proxypadDeployerSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as staking from "./staking";
export type { staking };
import type * as utils from "./utils";
export type { utils };
export type { CasterNFT } from "./CasterNFT";
export type { LockerFactory } from "./LockerFactory";
export type { LpLocker } from "./LpLocker";
export type { PrizePool } from "./PrizePool";
export type { RoyaltyBank } from "./RoyaltyBank";
export type { Ticket } from "./Ticket";
