/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokenFactorySol from "./TokenFactory.sol";
export type { tokenFactorySol };
export type { InstantLiquidityToken } from "./InstantLiquidityToken";
export type { MetalFunFactory } from "./MetalFunFactory";
