/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRoyaltyContract__factory } from "./IRoyaltyContract__factory";
export { IStakeNFT__factory } from "./IStakeNFT__factory";
