/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as proxypadDeployerLpSol from "./ProxypadDeployerLP.sol";
export type { proxypadDeployerLpSol };
