/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ProxypadDeployerLPInterface extends utils.Interface {
  functions: {
    "deploy(string,string,uint256,uint256,uint256,address)": FunctionFragment;
    "updateNFTManager(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "deploy" | "updateNFTManager"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deploy",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateNFTManager",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "deploy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateNFTManager",
    data: BytesLike
  ): Result;

  events: {
    "NewToken(address,address,string,string,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewToken"): EventFragment;
}

export interface NewTokenEventObject {
  token: string;
  creator: string;
  tokenName: string;
  tokenSymbol: string;
  maxSupply: BigNumber;
}
export type NewTokenEvent = TypedEvent<
  [string, string, string, string, BigNumber],
  NewTokenEventObject
>;

export type NewTokenEventFilter = TypedEventFilter<NewTokenEvent>;

export interface ProxypadDeployerLP extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ProxypadDeployerLPInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deploy(
      _name: PromiseOrValue<string>,
      _symbol: PromiseOrValue<string>,
      _maxSupply: PromiseOrValue<BigNumberish>,
      _liquidity: PromiseOrValue<BigNumberish>,
      _backingLiquidity: PromiseOrValue<BigNumberish>,
      owner: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateNFTManager(
      _newNFTManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  deploy(
    _name: PromiseOrValue<string>,
    _symbol: PromiseOrValue<string>,
    _maxSupply: PromiseOrValue<BigNumberish>,
    _liquidity: PromiseOrValue<BigNumberish>,
    _backingLiquidity: PromiseOrValue<BigNumberish>,
    owner: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateNFTManager(
    _newNFTManager: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    deploy(
      _name: PromiseOrValue<string>,
      _symbol: PromiseOrValue<string>,
      _maxSupply: PromiseOrValue<BigNumberish>,
      _liquidity: PromiseOrValue<BigNumberish>,
      _backingLiquidity: PromiseOrValue<BigNumberish>,
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber]>;

    updateNFTManager(
      _newNFTManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "NewToken(address,address,string,string,uint256)"(
      token?: PromiseOrValue<string> | null,
      creator?: PromiseOrValue<string> | null,
      tokenName?: null,
      tokenSymbol?: null,
      maxSupply?: null
    ): NewTokenEventFilter;
    NewToken(
      token?: PromiseOrValue<string> | null,
      creator?: PromiseOrValue<string> | null,
      tokenName?: null,
      tokenSymbol?: null,
      maxSupply?: null
    ): NewTokenEventFilter;
  };

  estimateGas: {
    deploy(
      _name: PromiseOrValue<string>,
      _symbol: PromiseOrValue<string>,
      _maxSupply: PromiseOrValue<BigNumberish>,
      _liquidity: PromiseOrValue<BigNumberish>,
      _backingLiquidity: PromiseOrValue<BigNumberish>,
      owner: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateNFTManager(
      _newNFTManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deploy(
      _name: PromiseOrValue<string>,
      _symbol: PromiseOrValue<string>,
      _maxSupply: PromiseOrValue<BigNumberish>,
      _liquidity: PromiseOrValue<BigNumberish>,
      _backingLiquidity: PromiseOrValue<BigNumberish>,
      owner: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateNFTManager(
      _newNFTManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
